CREATE TABLE SALARIES(
ID NUMBER PRIMARY KEY NOT NULL,
EMPLOYEE_ID NUMBER NOT NULL CONSTRAINT SALARY_EMPLOYEE  REFERENCES EMPLOYEES(id),
PROJECT_ID NUMBER NOT NULL CONSTRAINT SALARY_PROJECT  REFERENCES PROJECTS(id),
SALARY NUMBER(10,2) 
);


CREATE TABLE PROJECTS(
ID NUMBER PRIMARY KEY NOT NULL,
CODE VARCHAR2(255) NOT NULL,
MANAGER_ID NUMBER NOT NULL CONSTRAINT MANAGER_PROJECT  REFERENCES EMPLOYEES(id),
BUDGET NUMBER(10,2)NOT NULL,
DATE_OF_BIGINNING DATE ,
DATE_OF_ENDING DATE
);

SELECT * FROM EMPLOYEES;
CREATE TABLE EMPLOYEES(
ID NUMBER PRIMARY KEY ,
MANAGER_ID NUMBER NOT NULL CONSTRAINT MANAGER REFERENCES EMPLOYEES(id),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR(255) NOT NULL
);

/* 1-*Write a SQL query to fetch project code and count of employees (code, counter) sorted by counter in ascending order. example 48205501099, 4*/
SELECT P.CODE,COUNT(E.ID) FROM PROJECTS P INNER JOIN   EMPLOYEES E ON P.MANAGER_ID=E.ID

/* 2 -Write a query to fetch employee names of those who are not assigned to any project*/
SELECT E.FULL_NAME FROM PROJECTS P LEFT OUTER JOIN   EMPLOYEES E ON P.MANAGER_ID=E.ID


